name: Deploy Windows 11 Virtual Desktops

on: [push]

jobs:
  deploy-vms:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group rrtestResourceGroup \
          --template-file .github/workflows/main.bicep \
          --parameters vmAdminUsername='${{ secrets.VM_ADMIN_USERNAME }}' vmAdminPassword='${{ secrets.VM_ADMIN_PASSWORD }}'
